### ISSUE TITLE
#20 broken Riemann input module

### ISSUE THREAD

**Issue by parmus** [spotify/ffwd#26]
#20 broke Riemann in a number of way. Currently ffwd-java throws exceptions like this on startup:

```
14:34:32.722 [main] ERROR com.spotify.ffwd.FastForwardAgent - Error in agent, exiting
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Could not find a suitable constructor in com.spotify.ffwd.riemann.RiemannSerialization. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.spotify.ffwd.riemann.RiemannSerialization.class(RiemannSerialization.java:42)
  while locating com.spotify.ffwd.riemann.RiemannSerialization
    for field at com.spotify.ffwd.riemann.RiemannFrameDecoder.serializer(RiemannFrameDecoder.java:29)
  at com.spotify.ffwd.riemann.RiemannInputPlugin$1.configure(RiemannInputPlugin.java:77) (via modules: com.spotify.ffwd.input.InputManagerModule$1 -> com.spotify.ffwd.riemann.RiemannInputPlugin$1)

2) Could not find a suitable constructor in com.spotify.ffwd.riemann.RiemannSerialization. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.spotify.ffwd.riemann.RiemannSerialization.class(RiemannSerialization.java:42)
  while locating com.spotify.ffwd.riemann.RiemannSerialization
    for field at com.spotify.ffwd.riemann.RiemannDatagramDecoder.serializer(RiemannDatagramDecoder.java:26)
  at com.spotify.ffwd.riemann.RiemannInputPlugin$1.configure(RiemannInputPlugin.java:79) (via modules: com.spotify.ffwd.input.InputManagerModule$1 -> com.spotify.ffwd.riemann.RiemannInputPlugin$1)

3) Could not find a suitable constructor in com.spotify.ffwd.riemann.RiemannSerialization. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.spotify.ffwd.riemann.RiemannSerialization.class(RiemannSerialization.java:42)
  while locating com.spotify.ffwd.riemann.RiemannSerialization
    for field at com.spotify.ffwd.riemann.RiemannMessageDecoder.serializer(RiemannMessageDecoder.java:26)
  at com.spotify.ffwd.riemann.RiemannInputPlugin$1.configure(RiemannInputPlugin.java:80) (via modules: com.spotify.ffwd.input.InputManagerModule$1 -> com.spotify.ffwd.riemann.RiemannInputPlugin$1)

4) Could not find a suitable constructor in com.spotify.ffwd.riemann.RiemannSerialization. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.spotify.ffwd.riemann.RiemannSerialization.class(RiemannSerialization.java:42)
  while locating com.spotify.ffwd.riemann.RiemannSerialization
    for field at com.spotify.ffwd.riemann.RiemannFrameDecoder.serializer(RiemannFrameDecoder.java:29)
  at com.spotify.ffwd.riemann.RiemannInputPlugin$1.configure(RiemannInputPlugin.java:77) (via modules: com.spotify.ffwd.input.InputManagerModule$1 -> com.spotify.ffwd.riemann.RiemannInputPlugin$1)

5) Could not find a suitable constructor in com.spotify.ffwd.riemann.RiemannSerialization. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.spotify.ffwd.riemann.RiemannSerialization.class(RiemannSerialization.java:42)
  while locating com.spotify.ffwd.riemann.RiemannSerialization
    for field at com.spotify.ffwd.riemann.RiemannDatagramDecoder.serializer(RiemannDatagramDecoder.java:26)
  at com.spotify.ffwd.riemann.RiemannInputPlugin$1.configure(RiemannInputPlugin.java:79) (via modules: com.spotify.ffwd.input.InputManagerModule$1 -> com.spotify.ffwd.riemann.RiemannInputPlugin$1)

6) Could not find a suitable constructor in com.spotify.ffwd.riemann.RiemannSerialization. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.spotify.ffwd.riemann.RiemannSerialization.class(RiemannSerialization.java:42)
  while locating com.spotify.ffwd.riemann.RiemannSerialization
    for field at com.spotify.ffwd.riemann.RiemannMessageDecoder.serializer(RiemannMessageDecoder.java:26)
  at com.spotify.ffwd.riemann.RiemannInputPlugin$1.configure(RiemannInputPlugin.java:80) (via modules: com.spotify.ffwd.input.InputManagerModule$1 -> com.spotify.ffwd.riemann.RiemannInputPlugin$1)

6 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:225)
        at com.spotify.ffwd.AgentCore.setupPrimaryInjector(AgentCore.java:346)
        at com.spotify.ffwd.AgentCore.run(AgentCore.java:107)
        at com.spotify.ffwd.FastForwardAgent.main(FastForwardAgent.java:82)
```

**Comment by Azim0313** [comment]
Hey guys,

Can you help us understand this issue is also related to this very own bug

05:35:25.755 [main] ERROR com.spotify.ffwd.FastForwardAgent - Error in agent, exiting
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

Above is the error we are facing

Cheers,
